# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ossint < Formula
  desc "A tool OSINT for Github OSS"
  homepage "https://github.com/kiwamizamurai/ossint"
  version "0.4.0"

  on_macos do
    on_intel do
      url "https://github.com/kiwamizamurai/ossint/releases/download/v0.4.0/ossint_Darwin_x86_64.tar.gz"
      sha256 "5ed67a46902977642682b249e8f7ea094698f5c189d8a147c454c65997ec48cb"

      def install
        bin.install "ossint"
      end
    end
    on_arm do
      url "https://github.com/kiwamizamurai/ossint/releases/download/v0.4.0/ossint_Darwin_arm64.tar.gz"
      sha256 "2c2b498f57f76bbc48a343b241b7d7c1e71a2f8d80432cc7374fbf54a6ad6d7e"

      def install
        bin.install "ossint"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kiwamizamurai/ossint/releases/download/v0.4.0/ossint_Linux_x86_64.tar.gz"
        sha256 "0a2cb8d3c40d0dbb950df8501facc2fba4c02953e1b53f09355ba0884b88b34e"

        def install
          bin.install "ossint"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kiwamizamurai/ossint/releases/download/v0.4.0/ossint_Linux_arm64.tar.gz"
        sha256 "39bdd309a8d0abd4ff251eb5817b63b006f63b9d0d96d2e0aaa4c41711ea4606"

        def install
          bin.install "ossint"
        end
      end
    end
  end
end
